-- 1/3: empresas, usuarios y catalogo.
-- Ejecutar primero en PostgreSQL.

CREATE TABLE companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    full_name varchar(160) NOT NULL,
    email varchar(255),
    dni varchar(8),
    auth_subject varchar(64),
    password_hash varchar(255),
    role varchar(30) NOT NULL DEFAULT 'admin',
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE audit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    user_id integer REFERENCES users(id),
    actor_name varchar(160),
    action varchar(40) NOT NULL,
    entity_type varchar(60) NOT NULL,
    entity_id integer,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip_address varchar(45),
    user_agent varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(160) NOT NULL,
    email varchar(255),
    phone varchar(40),
    document_number varchar(30),
    address varchar(255),
    customer_type varchar(20) NOT NULL DEFAULT 'individual',
    contact_name varchar(160),
    industry varchar(120),
    preferred_contact_method varchar(20) NOT NULL DEFAULT 'whatsapp',
    notes text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(100) NOT NULL,
    description varchar(255)
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    category_id integer REFERENCES categories(id),
    sku varchar(40) NOT NULL,
    name varchar(160) NOT NULL,
    description text,
    price numeric(12, 2) NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    min_stock integer NOT NULL DEFAULT 5,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE employees (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    full_name varchar(160) NOT NULL,
    email varchar(255),
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    uploaded_by_id integer REFERENCES users(id),
    title varchar(160) NOT NULL,
    filename varchar(255) NOT NULL UNIQUE,
    original_filename varchar(255) NOT NULL,
    mime_type varchar(120) NOT NULL,
    size_bytes integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE branches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(160) NOT NULL,
    address varchar(255),
    latitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_branches_company_name UNIQUE (company_id, name),
    CONSTRAINT ck_branches_peru_latitude CHECK (latitude >= -18.5 AND latitude <= 0.2),
    CONSTRAINT ck_branches_peru_longitude CHECK (longitude >= -81.5 AND longitude <= -68.5)
);

CREATE INDEX ix_branches_company_id ON branches (company_id);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_dni ON users (dni);
CREATE UNIQUE INDEX ix_users_auth_subject ON users (auth_subject);
CREATE INDEX ix_users_company_id ON users (company_id);
CREATE INDEX ix_audit_logs_company_id ON audit_logs (company_id);
CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);
CREATE INDEX ix_audit_logs_entity_type ON audit_logs (entity_type);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX ix_customers_company_id ON customers (company_id);
CREATE INDEX ix_customers_name ON customers (name);
CREATE INDEX ix_categories_company_id ON categories (company_id);
CREATE INDEX ix_products_company_id ON products (company_id);
CREATE INDEX ix_products_category_id ON products (category_id);
CREATE INDEX ix_products_sku ON products (sku);
CREATE INDEX ix_products_name ON products (name);
CREATE INDEX ix_employees_company_id ON employees (company_id);
CREATE INDEX ix_documents_company_id ON documents (company_id);
CREATE INDEX ix_documents_uploaded_by_id ON documents (uploaded_by_id);
CREATE INDEX ix_documents_created_at ON documents (created_at);