-- 2/3: ventas, pagos e inventario.
-- Ejecutar despues de 01_core.sql.

CREATE TABLE sales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    customer_id integer REFERENCES customers(id),
    created_by_id integer REFERENCES users(id),
    sale_number varchar(30) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'completed',
    subtotal numeric(12, 2) NOT NULL,
    discount numeric(12, 2) NOT NULL DEFAULT 0.00,
    tax numeric(12, 2) NOT NULL,
    total numeric(12, 2) NOT NULL,
    notes varchar(500),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sale_details (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES products(id),
    product_name varchar(160) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    line_total numeric(12, 2) NOT NULL
);

CREATE TABLE payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    amount numeric(12, 2) NOT NULL,
    method varchar(30) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'paid',
    paid_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inventory_movements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    product_id integer NOT NULL REFERENCES products(id),
    sale_id integer REFERENCES sales(id),
    purchase_id integer,
    movement_type varchar(20) NOT NULL,
    quantity integer NOT NULL,
    stock_after integer NOT NULL,
    note varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sales_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    sale_id integer NOT NULL UNIQUE REFERENCES sales(id) ON DELETE CASCADE,
    document_type varchar(20) NOT NULL,
    document_number varchar(30) NOT NULL UNIQUE,
    customer_name varchar(160) NOT NULL,
    customer_document varchar(30),
    customer_address varchar(255),
    currency varchar(3) NOT NULL DEFAULT 'PEN',
    subtotal numeric(12, 2) NOT NULL,
    discount numeric(12, 2) NOT NULL,
    tax numeric(12, 2) NOT NULL,
    total numeric(12, 2) NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sales_document_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL REFERENCES sales_documents(id) ON DELETE CASCADE,
    product_name varchar(160) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    line_total numeric(12, 2) NOT NULL
);

CREATE TABLE purchases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    created_by_id integer REFERENCES users(id),
    purchase_number varchar(30) NOT NULL UNIQUE,
    supplier_name varchar(160) NOT NULL,
    supplier_document_number varchar(30),
    supplier_address varchar(255),
    created_by_name varchar(160) NOT NULL,
    total numeric(12, 2) NOT NULL,
    notes varchar(500),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE purchase_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id integer NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES products(id),
    product_name varchar(160) NOT NULL,
    product_sku varchar(40) NOT NULL,
    quantity integer NOT NULL,
    unit_cost numeric(12, 2) NOT NULL,
    line_total numeric(12, 2) NOT NULL
);

ALTER TABLE inventory_movements
    ADD CONSTRAINT fk_inventory_movements_purchase
    FOREIGN KEY (purchase_id) REFERENCES purchases(id);

CREATE UNIQUE INDEX ix_sales_sale_number ON sales (sale_number);
CREATE UNIQUE INDEX ix_sales_documents_document_number ON sales_documents (document_number);
CREATE INDEX ix_sales_documents_company_id ON sales_documents (company_id);
CREATE INDEX ix_sales_documents_sale_id ON sales_documents (sale_id);
CREATE INDEX ix_sales_document_items_document_id ON sales_document_items (document_id);
CREATE UNIQUE INDEX ix_purchases_purchase_number ON purchases (purchase_number);
CREATE INDEX ix_purchases_company_id ON purchases (company_id);
CREATE INDEX ix_purchases_created_at ON purchases (created_at);
CREATE INDEX ix_purchase_items_purchase_id ON purchase_items (purchase_id);
CREATE INDEX ix_purchase_items_product_id ON purchase_items (product_id);
CREATE INDEX ix_sales_company_id ON sales (company_id);
CREATE INDEX ix_sales_customer_id ON sales (customer_id);
CREATE INDEX ix_sales_created_at ON sales (created_at);
CREATE INDEX ix_sale_details_sale_id ON sale_details (sale_id);
CREATE INDEX ix_sale_details_product_id ON sale_details (product_id);
CREATE INDEX ix_payments_sale_id ON payments (sale_id);
CREATE INDEX ix_inventory_movements_company_id ON inventory_movements (company_id);
CREATE INDEX ix_inventory_movements_product_id ON inventory_movements (product_id);
CREATE INDEX ix_inventory_movements_created_at ON inventory_movements (created_at);
CREATE INDEX ix_inventory_movements_purchase_id ON inventory_movements (purchase_id);