-- 2/3: ventas, pagos e inventario.
-- Ejecutar despues de 01_core.sql.

CREATE TABLE sales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    customer_id integer REFERENCES customers(id),
    created_by_id integer REFERENCES users(id),
    sale_number varchar(30) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'completed',
    subtotal numeric(12, 2) NOT NULL,
    discount numeric(12, 2) NOT NULL DEFAULT 0.00,
    tax numeric(12, 2) NOT NULL,
    total numeric(12, 2) NOT NULL,
    notes varchar(500),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sale_details (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES products(id),
    product_name varchar(160) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    line_total numeric(12, 2) NOT NULL
);

CREATE TABLE payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    amount numeric(12, 2) NOT NULL,
    method varchar(30) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'paid',
    paid_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inventory_movements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    product_id integer NOT NULL REFERENCES products(id),
    sale_id integer REFERENCES sales(id),
    movement_type varchar(20) NOT NULL,
    quantity integer NOT NULL,
    stock_after integer NOT NULL,
    note varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ix_sales_sale_number ON sales (sale_number);
CREATE INDEX ix_sales_company_id ON sales (company_id);
CREATE INDEX ix_sales_customer_id ON sales (customer_id);
CREATE INDEX ix_sales_created_at ON sales (created_at);
CREATE INDEX ix_sale_details_sale_id ON sale_details (sale_id);
CREATE INDEX ix_sale_details_product_id ON sale_details (product_id);
CREATE INDEX ix_payments_sale_id ON payments (sale_id);
CREATE INDEX ix_inventory_movements_company_id ON inventory_movements (company_id);
CREATE INDEX ix_inventory_movements_product_id ON inventory_movements (product_id);
CREATE INDEX ix_inventory_movements_created_at ON inventory_movements (created_at);