-- 3/3: datasets, analisis, Bayes, insights e informes.
-- Ejecutar despues de 01_core.sql y 02_sales_inventory.sql.

CREATE TABLE analytics_datasets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(160) NOT NULL,
    description text,
    source_type varchar(40) NOT NULL,
    created_by_id integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dataset_variables (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id integer NOT NULL REFERENCES analytics_datasets(id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    display_name varchar(160) NOT NULL,
    data_type varchar(30) NOT NULL,
    variable_role varchar(30) NOT NULL,
    position integer NOT NULL DEFAULT 0,
    configuration jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE dataset_observations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id integer NOT NULL REFERENCES analytics_datasets(id) ON DELETE CASCADE,
    external_key varchar(160),
    observed_at timestamptz,
    observation_data jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE statistical_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    dataset_id integer NOT NULL REFERENCES analytics_datasets(id),
    name varchar(160) NOT NULL,
    analysis_type varchar(40) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'pending',
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by_id integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE analysis_variables (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer NOT NULL REFERENCES statistical_analyses(id) ON DELETE CASCADE,
    variable_id integer NOT NULL REFERENCES dataset_variables(id),
    analysis_role varchar(30) NOT NULL DEFAULT 'input',
    UNIQUE (analysis_id, variable_id, analysis_role)
);

CREATE TABLE statistical_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer NOT NULL REFERENCES statistical_analyses(id) ON DELETE CASCADE,
    variable_id integer REFERENCES dataset_variables(id),
    metric varchar(80) NOT NULL,
    result jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bayesian_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(160) NOT NULL,
    question text NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'pending',
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by_id integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bayesian_evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer NOT NULL REFERENCES bayesian_analyses(id) ON DELETE CASCADE,
    name varchar(160) NOT NULL,
    evidence_type varchar(40) NOT NULL,
    observed_value jsonb NOT NULL,
    likelihood numeric(12, 8),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bayesian_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer NOT NULL REFERENCES bayesian_analyses(id) ON DELETE CASCADE,
    hypothesis text NOT NULL,
    prior_probability numeric(12, 8) NOT NULL,
    posterior_probability numeric(12, 8) NOT NULL,
    calculation jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE insights (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    analysis_id integer REFERENCES statistical_analyses(id),
    title varchar(200) NOT NULL,
    description text NOT NULL,
    severity varchar(24) NOT NULL DEFAULT 'info',
    status varchar(24) NOT NULL DEFAULT 'new',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE insight_evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insight_id integer NOT NULL REFERENCES insights(id) ON DELETE CASCADE,
    result_id integer REFERENCES statistical_results(id),
    description text NOT NULL,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id),
    name varchar(160) NOT NULL,
    report_type varchar(40) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'pending',
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    output_url text,
    created_by_id integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    generated_at timestamptz
);

CREATE INDEX ix_analytics_datasets_company_id ON analytics_datasets (company_id);
CREATE INDEX ix_dataset_variables_dataset_id ON dataset_variables (dataset_id);
CREATE INDEX ix_dataset_observations_dataset_id ON dataset_observations (dataset_id);
CREATE INDEX ix_statistical_analyses_company_id ON statistical_analyses (company_id);
CREATE INDEX ix_statistical_analyses_dataset_id ON statistical_analyses (dataset_id);
CREATE INDEX ix_analysis_variables_analysis_id ON analysis_variables (analysis_id);
CREATE INDEX ix_analysis_variables_variable_id ON analysis_variables (variable_id);
CREATE INDEX ix_statistical_results_analysis_id ON statistical_results (analysis_id);
CREATE INDEX ix_statistical_results_variable_id ON statistical_results (variable_id);
CREATE INDEX ix_bayesian_analyses_company_id ON bayesian_analyses (company_id);
CREATE INDEX ix_bayesian_evidence_analysis_id ON bayesian_evidence (analysis_id);
CREATE INDEX ix_bayesian_results_analysis_id ON bayesian_results (analysis_id);
CREATE INDEX ix_insights_company_id ON insights (company_id);
CREATE INDEX ix_insights_analysis_id ON insights (analysis_id);
CREATE INDEX ix_insight_evidence_insight_id ON insight_evidence (insight_id);
CREATE INDEX ix_insight_evidence_result_id ON insight_evidence (result_id);
CREATE INDEX ix_reports_company_id ON reports (company_id);